apikey = "Key" # you can get your key here: https://osu.ppy.sh/p/api
nickname = "Username" # osu username, get it here: https://osu.ppy.sh/p/irc
password = "Server Password" # osu server pass, get it here: https://osu.ppy.sh/p/irc
mods = {
    "0": "Nomod",
    "1": "NF",
    "2": "EZ",
    "8": "HD",
    "16": "HR",
    "32": "SD",
    "64": "DT",
    "128": "RX",
    "256": "HT",
    "512": "NC",
    "1024": "FL",
    "2048": "AU",
    "4096": "SO",
    "8192": "AP",
    "16384": "PF"
    }
mods_from_words_to_abb = {
    "NoFail": "NF",
    "Easy": "EZ",
    "Hidden": "HD",
    "HardRock": "HR",
    "SuddenDeath": "SD",
    "DoubleTime": "DT",
    "Relax": "RX",
    "HalfTime": "HT",
    "Flashlight": "FL",
    "Nightcore": "NC",
    "Auto": "AU",
    "SpunOut": "SO",
    "AutoPilot": "AP",
    "Perfect": "PF"
}

country_abb = {
    ########AFRICA#########
    "DZ": "Algeria",
    "AO": "Angola",
    "BJ": "Benin",
    "BW": "Botswana",
    "BF": "Burkina Faso",
    "BI": "Burundi",
    "CM": "Cameroon",
    "CV": "Cape Verde",
    "CF": "Central African Rrepublic",
    "TD": "Chad",
    "KM": "Comoros",
    "CG": "Congo",
    "CD": "Congo, Democratic Republic of",
    "CI": "Côte d'Ivoire",
    "DJ": "Djibouti",
    "EG": "Egypt",
    "GQ": "Equatorial Guinea",
    "ER": "Eritrea",
    "ET": "Ethiopia",
    "GA": "Gabon",
    "GM": "Gambia",
    "GH": "Ghana",
    "GN": "Guinea",
    "GW": "Guinea-Bissau",
    "KE": "Kenya",
    "LS": "Lesotho",
    "LR": "Liberia",
    "LY": "Libyan Arab Jamahiriya",
    "MG": "Madagascar",
    "MW": "Malawi",
    "ML": "Mali",
    "MR": "Mauritania",
    "MU": "Mauritius",
    "YT": "Mayotte",
    "MA": "Morocco",
    "MZ": "Mozambique",
    "NA": "Namibia",
    "NE": "Niger",
    "NG": "Nigeria",
    "RE": "Reunion",
    "RW": "Rwanda",
    "SH": "Saint Helena",
    "ST": "Sao Tome and Principe",
    "SN": "Senegal",
    "SC": "Seychelles",
    "SL": "Sierra Leone",
    "SO": "Somalia",
    "ZA": "South Africa",
    "SS": "South Sudan",
    "SD": "Sudan",
    "SZ": "Swaziland",
    "TZ": "Tanzania",
    "TG": "Togo",
    "TN": "Tunisia",
    "UG": "Uganda",
    "EH": "Western Sahara",
    "ZM": "Zambia",
    "ZW": "Zimbabwe",
    ########ANTARCTICA############
    "AQ": "Antarctica",
    "BV": "Bouvet Island",
    "TF": "French Southern Territories",
    "HM": "Heard Island and McDonald Islands",
    "GS": "South Georgia and the South Sandwich Islands",
    #########AUSTRALIA&OCEANIA###########
    "AS": "American Samoa",
    "AU": "Australia",
    "CK": "Cook Islands",
    "FJ": "Fiji",
    "PF": "French Polynesia",
    "GU": "Guam",
    "KI": "Kiribati",
    "MH": "Marshall Islands",
    "FM": "Micronesia",
    "NR": "Nauru",
    "NC": "New Caledonia",
    "NZ": "New Zealand",
    "NU": "Niue",
    "NF": "Nortfolk Island",
    "MP": "Northern Mariana Islands",
    "PW": "Palau",
    "PG": "Papua New Guinea",
    "PN": "Pitcairn Islands",
    "WS": "Samoa",
    "SB": "Solomon Islands",
    "TK": "Tokelau",
    "TO": "Tonga, Kingdom of",
    "TV": "Tuvalu",
    "UM": "United States Minor Outlying Islands",
    "VU": "Vanuatu",
    "WF": "Wallis and Futuna",
    ##########ASIA##########
    "AF": "Afghanistan",
    "AZ": "Azerbaijan",
    "BH": "Bahrain",
    "BD": "Bangladesh",
    "BT": "Bhutan",
    "IO": "British Indian Ocean Territory",
    "BN": "Brunei Darussalam",
    "KH": "Cambodia",
    "CN": "China, People's Republic of",
    "CX": "Christmas Island",
    "CC": "Cocos (Keeling) Islands",
    "CY": "Cyprus",
    "GE": "Georgia",
    "HK": "Honk Kong",
    "IN": "India",
    "ID": "Indonesia",
    "IR": "Iran, Islamic Republic of",
    "IQ": "Iraq",
    "IL": "Israel",
    "JP": "Japan",
    "JO": "Jordan",
    "KZ": "Kazakhstan",
    "KP": "Korea, Democratic People's Republic of",
    "KR": "Korea, Republic of",
    "KW": "Kuwait",
    "KG": "Kyrgyzstan",
    "LA": "Lao People's Democratic Republic",
    "LB": "Lebanon",
    "MO": "Macao",
    "MY": "Malaysia",
    "MV": "Maldives",
    "MN": "Mongolia",
    "MM": "Myanmar",
    "NP": "Nepal",
    "OM": "Oman",
    "PK": "Pakistan",
    "PS": "Palestinian Territory",
    "PH": "Philippines",
    "QA": "Qatar",
    "SA": "Saudi Arabia",
    "SG": "Singapore",
    "LK": "Sri Lanka",
    "SY": "Syrian Arab Republic",
    "TW": "Taiwan",
    "TJ": "Tajikistan",
    "TH": "Thailand",
    "TL": "Timor-Leste",
    "TR": "Turkey",
    "TM": "Turkmenistan",
    "AE": "United Arab Emirates",
    "UZ": "Uzbekistan",
    "VN": "Vietnam",
    "YE": "Yemen",
    ###########EUROPE#############
    "AX": "Alan Islands",
    "AL": "Albania",
    "AD": "Andorra",
    "AM": "Armenia",
    "AT": "Austria",
    "BY": "Belarus",
    "BE": "Belgium",
    "BA": "Bosnia and Herzegovina",
    "BG": "Bulgaria",
    "HR": "Croatia",
    "CZ": "Czesh Republic",
    "DK": "Denmark",
    "EE": "Estonia",
    "FO": "Faroe Islands",
    "FI": "Finland",
    "FR": "France",
    "DE": "Germany",
    "GI": "Gibraltar",
    "GR": "Greece",
    "GG": "Guernsey",
    "VA": "Holy See (Vatican City State)",
    "HU": "Hungary",
    "IS": "Iceland",
    "IE": "Ireland",
    "IM": "Isle of Man",
    "IT": "Italy",
    "JE": "Jersey",
    "LV": "Latvia",
    "LI": "Liechtenstein",
    "LT": "Lithuania",
    "LU": "Luxembourg",
    "MK": "Macedonia",
    "MT": "Malta",
    "MD": "Moldova",
    "MC": "Monaco",
    "ME": "Montenegro",
    "NL": "Netherlands",
    "NO": "Norway",
    "PL": "Poland",
    "PT": "Portugal",
    "RO": "Romania",
    "RU": "Russia",
    "SM": "San Marino",
    "RS": "Serbia",
    "SK": "Slovakia",
    "SI": "Slovenia",
    "ES": "Spain",
    "SJ": "Svalbard & Jan Mayen Islands",
    "SE": "Sweden",
    "CH": "Switzerland",
    "UA": "Ukraine",
    "GB": "United Kingdom",
    ###############NORTH AMERICA#############
    "AI": "Anguilla",
    "AW": "Aruba",
    "BQ": "Bonaire, Sint Eustatius and Saba",
    "CA": "Canada",
    "CU": "Cuba",
    "CW": "Curaçao",
    "DM": "Dominica",
    "DO": "Dominican Republic",
    "SV": "El Salvador",
    "GL": "Greenland",
    "GD": "Grenada",
    "GP": "Guadeloupe",
    "GT": "Guatemala",
    "HT": "Haiti",
    "HN": "Honduras",
    "JM": "Jamaica",
    "MQ": "Martinique",
    "MX": "Mexico",
    "MS": "Montserrat",
    "AN": "Netherlands Antilles",
    "NI": "Nicaragua",
    "PA": "Panama",
    "PR": "Puerto Rico",
    "BL": "Saint Barthelemy",
    "KN": "Saint Kitts and Nevis",
    "LC": "Saint Lucia",
    "MF": "Saint Martin",
    "PM": "Saint Pierre and Miquelon",
    "VC": "Saint Vincent and the Grenadines",
    "SX": "Netherlands",
    "TT": "Trinidad and Tobago",
    "TC": "Turks and Caicos Islands",
    "US": "United States of America",
    "VI": "United States Virgin Islands",
    #######SOUTHAMERICA########
    "AR": "Argentina",
    "BO": "Bolivia",
    "BR": "Brazil",
    "CL": "Chile",
    "CO": "Colombia",
    "EC": "Ecuador",
    "FK": "Falkland Islands",
    "GF": "French Guiana",
    "GY": "Guyana",
    "PY": "Paraguay",
    "PE": "Peru",
    "SR": "Suriname",
    "UY": "Uruguay",
    "VE": "Venezuela"
}
